/*
 * Copyright (c) 2025 Nordic Semiconductor ASA
 *
 * SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
 */

#define WATCHDOG_SYSTEM_WORKQUEUE_FEED_INTERVAL_MSEC	\
	(CONFIG_SLM_WATCHDOG_SYSTEM_WORKQUEUE_TIMEOUT_MSEC / 2)
#define WATCHDOG_STATS_FEED_INTERVAL_MSEC	(CONFIG_SLM_STATS_WATCHDOG_TIMEOUT_MSEC / 2)
